//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Projects/Grammar_With_ANTLR4_Unity/Grammar_Project/Assets/Simple_Grammar (ANTLR)/Simple_Grammar.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="Simple_GrammarParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface ISimple_GrammarListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="Simple_GrammarParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStart([NotNull] Simple_GrammarParser.StartContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Simple_GrammarParser.start"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStart([NotNull] Simple_GrammarParser.StartContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Simple_GrammarParser.s"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterS([NotNull] Simple_GrammarParser.SContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Simple_GrammarParser.s"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitS([NotNull] Simple_GrammarParser.SContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Simple_GrammarParser.t"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterT([NotNull] Simple_GrammarParser.TContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Simple_GrammarParser.t"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitT([NotNull] Simple_GrammarParser.TContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Simple_GrammarParser.a"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterA([NotNull] Simple_GrammarParser.AContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Simple_GrammarParser.a"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitA([NotNull] Simple_GrammarParser.AContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="Simple_GrammarParser.b"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterB([NotNull] Simple_GrammarParser.BContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="Simple_GrammarParser.b"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitB([NotNull] Simple_GrammarParser.BContext context);
}
